### ISSUE TITLE
[Feature] Implement sss javascript wrapper using WASM

### ISSUE THREAD

**Issue by oed** [3box/sss-wasm#1]
## Task
Implement a javascript wrapper around the [dsprenkles/sss](https://github.com/dsprenkels/sss/tree/master) library using Web Assembly. The dsprenkles/sss library is writeen in C. There is currently a [node.js wrapper](https://github.com/dsprenkels/sss-node) availiable, however this can not be run in a browser. Instead you should compile the C code to WASM and make a thin wrapper to call this WASM code from javascript that is usable in browsers, mobile browsers, as well as node.js. The implementation should have the same api as the node.js implmentation that is linked above.

## Acceptance criteria
- [ ] Implement a javascript library that can call the sss C code though WASM
- [ ] Make the implementation compatible with [sss-node](https://github.com/dsprenkels/sss-node), should work with the same [tests](https://github.com/dsprenkels/sss-node/blob/master/test.js) as in that repo
- [ ] Works in all major browsers, mobile and desktop, as well as node.js

## Technical details
Web Assembly allows you to compile *.c files into *.wasm files. The wasm file can then be loaded by a javascript file which can call the C functions. The *.wasm file is a binary that is compiled by a developer and distributed in this binary format to users loading a webpage which calls it's functions. There are some users that are on older browsers which doesn't support WASM yet. In their case using asm.js as the compile target should allow them to use the library. However that is not a requirement for this task.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.

 1. [@pfilippi24](https://gitcoin.co/profile/pfilippi24) 

 has committed to working on this project to be completed 4 weeks, 1 day from now.


@KamesCG, __please see the below comments / questions regarding approach for this ticket from the bounty hunter(s):__ 
- [@pfilippi24](https://gitcoin.co/profile/pfilippi24): Will use the node.js wrapper as starting point

**Comment by pfilippi24** [comment]
@oed Just to make this clear: You want the exact same API as the node.js wrapper?

Is it ok to provide a docker based build and have sss as submodule in the repo?

**Comment by oed** [comment]
@pfilippi24 yeah, exact same api would be great!
What do you mean by a docker based build? That you provide a docker for building the wasm module? Totally fine to include sss as a submodule!

**Comment by pfilippi24** [comment]
@oed Exactly, so there is no need for complicated environment setups and it's perfectly reproduceable.
Downside: Bigger downloads during first build.

**Comment by oed** [comment]
Cool, as long as the module remains small when you install it as a dependancy in another project :)

**Comment by pfilippi24** [comment]
just as a heads up: I'll submit a PR later today and we can discuss further based on that

**Comment by oed** [comment]
@pfilippi24 
> To get this working using webassembly we need to replace randombytes with something else

Could you elaborate, why is this the case?
No need to stress though, Do you think there is another solution?

**Comment by pfilippi24** [comment]
@bakaoh 
No, please you take it.
But can you show me your implementation of the crypto-secure random byte generation without system calls? Would be very interested in that.
Simply random wont cut the deal here.

**Comment by bakaoh** [comment]
@pfilippi24 -- i use window.crypto.getRandomValues/window.msCrypto.getRandomValues https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

**Comment by pfilippi24** [comment]
@bakaoh 
Good call, excludes Android, though.

**Comment by bakaoh** [comment]
@pfilippi24 --- yeah, android webview not support, but user can use chrome on android

**Comment by oed** [comment]
@bakaoh That's alright, the crypto api is what I would have gone with as well :)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 350.0 DAI (350.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@bakaoh](https://gitcoin.co/profile/bakaoh) 



@KamesCG please take a look at the submitted work:
* [PR](https://github.com/uport-project/sss-wasm/pull/2) by @bakaoh

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/uport-project/sss-wasm/1/481)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
$11,432.18 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 350.0 DAI (350.0 USD @ $1.0/DAI) attached to this issue has been approved & issued to @bakaoh.__  

 * Learn more at [on the Gitcoin Issue Details page](https://gitcoin.co/issue/uport-project/sss-wasm/1/481)
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $13,177.52 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
